services:
  journey-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: docker
      PROFILE: ""
      RUN_ID: "docker"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS:-false}"
    env_file:
      - ./docker/config/defaults.env
    depends_on: []
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./playwright-report:/app/playwright-report
    extra_hosts:
      - "front-office.lis.defra:host-gateway"
      - "back-office.lis.defra:host-gateway"
      - "mock-entra-id.lis.defra:host-gateway"
      - "mock-defra-ci.lis.defra:host-gateway"
      - "npm-local.lis.defra:host-gateway"
      - "nuget-local.lis.defra:host-gateway"
      - "fake-idp.lis.defra:host-gateway"
      - "fake-service.lis.defra:host-gateway"
    networks:
      - lis-dev_default

networks:
  lis-dev_default:
    external: true
