services:
  journey-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: docker
      PROFILE: ""
      RUN_ID: "docker"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS:-false}"
    env_file:
      - ./docker/config/defaults.env
    depends_on: []
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./playwright-report:/app/playwright-report
    networks:
      - lis-dev

networks:
  lis-dev:
    driver: bridge