name: Run Journey Tests on GitHub
description: 'Run journet tests for lis front and back office projects'

inputs:
  test:
    description: 'Choose Test suite'
    type: choice
    required: false
    default: ''
    options:
      - '@api'
      - '@ui'
      - '@frontoffice'
      - '@backoffice'
  tag:
    description: 'Choose test group'
    type: choice
    required: false
    default: ''
    options:
      - '@smoke'
      - '@e2e'
  slack-webhook-url:
    required: false

runs:
  using: "composite"
  steps:
    # Checkout the journey-tests repo
    - uses: actions/checkout@v4
      with:
        repository: DEFRA/lis-journey-tests
        path: lis-journey-tests

    # Setup Node
    - uses: actions/setup-node@v4
      with:
        node-version-file: lis-journey-tests/.nvmrc
        cache: npm

   # Install dependencies
    - name: Install dependencies
      working-directory: lis-journey-tests
      run: npm ci
      shell: bash

    # Install Playwright browsers
    - name: Install Playwright browsers
      working-directory: lis-journey-tests
      run: npx playwright install --with-deps
      shell: bash

    # Debug environment variables injected by CDP
    - name: Show environment variables
      shell: bash
      run: |
        echo "FRONTOFFICEURL:  $LIS_FRONTOFFICE_BASE_URL"
        echo "BACKOFFICEURL: $LIS_BACKOFFICE_BASE_URL"

    # Run Playwright tests
    - name: Run LIS Journey Tests
      working-directory: lis-journey-tests
      shell: bash
      env:
        ENVIRONMENT: dev   # CDP Portal will override this with dev/test/perf-test
      run: |
        FILTER=""
        if [[ -n "${{ inputs.test }}" ]]; then FILTER="${{ inputs.test }}"; fi
        if [[ -n "${{ inputs.tag }}" ]]; then
          if [[ -n "$FILTER" ]]; then FILTER="$FILTER|${{ inputs.tag }}"; else FILTER="${{ inputs.tag }}"; fi
        fi

        echo "Running tests with filter: $FILTER"

        if [[ -z "$FILTER" ]]; then
          npx playwright test --config=playwright.config.ts
        else
          npx playwright test --config=playwright.config.ts --grep="$FILTER"
        fi

    # Upload Allure report
    - name: Upload Allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: lis-journey-tests/allure-report

    # Upload Playwright HTML report
    - name: Upload Playwright HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: lis-journey-tests/playwright-report/html

    # Slack reporting is covered by CDP notification integration and is setup for DEV, Test and Ext-Test environments
